#ifndef _DAEMONS_H
#define _DAEMONS_H

#define ANSI_D          "/bin/daemons/ansid"
#define BALANCE_D       "/bin/daemons/balance_d"
#define BANISH_D        "/bin/daemons/banish_d"
#define BBOARD_D        "/bin/daemons/bboard_d"
#define CHANNEL_D       "/bin/daemons/channel_d"
#define CLAN_D          "/bin/daemons/clan_d"
#define CLOTHING_D      "/bin/daemons/clothingd"
#define CMD_D           "/bin/daemons/cmdd"
#define COMBAT_D        "/bin/daemons/combatd"
#define DEATH_D         "/bin/daemons/deathd"
#define DESC_D          "/bin/daemons/descs"
#define DONATION_D      "/bin/daemons/donation_d"
#define DRUNK_D         "/bin/daemons/drunkd"
#define ERROR_D         "/bin/daemons/remark"
#define FEEL_D          "/bin/daemons/feeld"
#define FINGER_D        "/bin/daemons/fingerd"
#define FINGER_D2       "/bin/daemons/finger_d"
#define FUMBLE_D        "/bin/daemons/fumbled"
#define GROUP_D         "/bin/daemons/groupd"
#define GUILD_D         "/bin/daemons/guildd"
#define HALLU_D         "/bin/daemons/hallucinations"
#define KINGDOM_D       "/bin/daemons/kingdom_d"
#define LEVELS_D        "/lib/levels"
#define MAIL_D          "/bin/daemons/maild"
#define MAPPER_D        "/bin/daemons/mapper_d"
#define MCHAR_D         "/bin/daemons/mchard"
#define MUDLOCK_D       "/bin/daemons/mudlock_d"
#define NAMING_D        "/bin/daemons/naming_d"
#define NATURE_D        "/bin/daemons/nature_d"
#define PARTY_D         "/bin/daemons/partyd"
#define PEACE_D         "/bin/daemons/peaced"
#define QUEST_D         "/bin/daemons/questd"
#define SHELL_D         "/bin/daemons/shelld"
#define SKILL_D         "/bin/daemons/skilld"
#define SMOKE_D         "/bin/daemons/smoked"
#define TELOPT_D        "/bin/daemons/telopt_d"
#define UNIQUE_D        "/bin/daemons/uniqued"
#define WHO_D           "/bin/daemons/who_d"

#endif
