/* This file should be used insted of directly referring to the
 * actual cloneable item files. The filenames of
 * the objects are likely to change occasionally, so this
 * should help in preventing the problems.
 */

#ifndef _GENERIC_ITEMS_H
#define _GENERIC_ITEMS_H

#define	GENERIC_BAG                     "/std/obj/bag"
#define	GENERIC_BBOARD                  "/std/obj/bboard"
#define	GENERIC_BEER                    "/std/obj/beer"
#define	GENERIC_BELL                    "/std/obj/bell"
#define	GENERIC_BENCH                   "/std/obj/bench"
#define	GENERIC_BLOOD_TRAIL             "/std/obj/blood_trail"
#define	GENERIC_CALTRAPS                "/std/obj/caltraps"
#define	GENERIC_CHEST                   "/std/obj/chest"
#define	GENERIC_COCA                    "/std/obj/coca"
#define	GENERIC_CUPBOARD                "/std/obj/cupboard"
#define GENERIC_DARK_TORCH              "/std/obj/darktorch"
#define	GENERIC_ENHANCED_FEELINGS       "/std/obj/enh_feelings"
#define	GENERIC_ELIXIR                  "/std/obj/elixir"
#define	GENERIC_FAKE_DEATH              "/std/obj/fake_death"
#define	GENERIC_FINGER_TOOL             "/std/obj/finger"
#define	GENERIC_FLOWERS                 "/std/obj/flowers"
#define	GENERIC_FROBOZZ_STATUE          "/std/obj/frobozz_statue"
#define	GENERIC_HEAL_OBJECT             "/std/obj/heal_object"
#define	GENERIC_HEAL_POTION             "/std/obj/heal_potion"
#define	GENERIC_KEY                     "/std/obj/key"
#define	GENERIC_LEO_NOTE                "/std/obj/leo_note"
#define	GENERIC_LORD_APPLICATION        "/std/obj/lord_application"
#define	GENERIC_LORD_BLESS              "/std/obj/lord_bless"
#define	GENERIC_LORD_CROWN              "/std/obj/lord_crown"
#define	GENERIC_LORD_LIST               "/std/obj/lord_list"
#define	GENERIC_MAGIC_LOCKPICK          "/std/obj/magic_lockpick"
#define	GENERIC_MAILBOX                 "/std/obj/mailbox"
#define	GENERIC_MAILBOX_FNAME           "std/obj/mailbox"
#define	GENERIC_MONEY_OBJECT            "/std/obj/money"
#define	GENERIC_NEWSPAPER               "/std/obj/newspaper"
#define	GENERIC_PIPE                    "/std/obj/pipe"
#define	GENERIC_POTION_FP               "/std/obj/potion_fp"
#define	GENERIC_POTION_FP_HP            "/std/obj/potion_fp_hp"
#define	GENERIC_PSILOCYBE               "/std/obj/psilocybe"
#define	GENERIC_PLAYER_LIST             "/std/obj/level_list"
#define	GENERIC_POINTED_STICK           "/std/obj/pointed_stick"
#define	GENERIC_QUEST_OBJECT            "/std/obj/quest_obj"
#define	GENERIC_RACE_TRANSFORMER        "/std/obj/race_transformer"
#define	GENERIC_RABBIT_PAW              "/std/obj/rabbit_paw"
#define	GENERIC_ROPE                    "/std/obj/rope"
#define	GENERIC_SCAR_REMOVAL_POTION	"/std/obj/scar_rem_potion"
#define	GENERIC_SCAR_ADD_POTION		"/std/obj/scar_add_potion"
#define	GENERIC_SCROLL_OF_HEALING       "/std/obj/scroll_of_healing"
#define	GENERIC_SCROLL_OF_RECALL        "/std/obj/scroll_of_recall"
#define	GENERIC_SHADOW_CLOAK            "/std/obj/shadow_cloak"
#define GENERIC_SHIT                    "/std/obj/shit"
#define	GENERIC_SIGN                    "/std/obj/sign"
#define	GENERIC_TIN                     "/std/obj/tin"
#define	GENERIC_TINNING_KIT             "/std/obj/tinning_kit"
#define	GENERIC_TRASHCAN                "/std/obj/trashcan"
#define	GENERIC_TORCH                   "/std/obj/torch"
#define	GENERIC_USER_GRAPH              "/std/obj/user_graph"
#define	GENERIC_WAND_OF_COLD            "/std/obj/wand_of_cold"

#endif
