#ifndef MAP_AREA_DEFS_H
#define MAP_AREA_DEFS_H

#include <city_name.h>

#define MAP_NOT_CENTER					0
#define MAP_CENTER					1

#define MAP_AREA_CITY_OF_TRISTEZA			1
#define MAP_AREA_TEMPLE_OF_TRISTEZA			2
#define MAP_AREA_TOWN_HALL_OF_TRISTEZA			3
#define MAP_AREA_COURT_HALL_OF_TRISTEZA			4
#define MAP_AREA_LORDS_GUILD_OF_TRISTEZA		5
#define MAP_AREA_HOSPITAL_OF_TRISTEZA			6
#define MAP_AREA_LAND_OF_THE_PURPLE_DINOSAUR		7
#define MAP_AREA_PLAYER_HOMES_OF_TRISTEZA		8
#define MAP_AREA_CASINO_OF_TRISTEZA			9
#define MAP_AREA_DUEL_ARENA_OF_TRISTEZA			10
#define MAP_AREA_BROTHERHOOD_VS_LORDS			11
#define MAP_AREA_KILRATHIAN_TOWER			12
#define MAP_AREA_VILLAGE_OF_THE_HILL_GIANTS		13
#define MAP_AREA_NEWBIE_PARK_OF_TRISTEZA		14
#define MAP_AREA_VALLEY_OF_THE_GIANTS			15
#define MAP_AREA_ADVENTURERS_GUILD_OF_TRISTEZA		16
#define MAP_AREA_MEMORIAL_PARK_OF_TRISTEZA		17
#define MAP_AREA_APARTMENTS_OF_TRISTEZA			18
#define MAP_AREA_PERFORMING_ARTS_CENTER_OF_TRISTEZA	19
#define MAP_AREA_TEMPLE_OF_SKERT			20
#define MAP_AREA_FINNISH_CLUB_OF_TRISTEZA		21
#define MAP_AREA_PLAINS_WEST_OF_TRISTEZA		22
#define MAP_AREA_FOREST_WEST_OF_TRISTEZA		23
#define MAP_AREA_LAND_OF_THE_MUTANT_TELETUBBIES		24
#define MAP_AREA_NORTHERN_HIGHWAY			25
#define MAP_AREA_VALLEY_OF_GORTHAUR			26
#define MAP_AREA_DEMON_WORLD				27
#define MAP_AREA_VORTEX_OF_SUFFERING			28
#define MAP_AREA_FOREST_SOUTH_OF_TRISTEZA		29
#define MAP_AREA_EAST_ROAD_OF_TRISTEZA			30
#define MAP_AREA_FOREST_SOUTHEAST_OF_TRISTEZA		31
#define MAP_AREA_SOUTHERN_HIGHWAY			32
#define MAP_AREA_WONDERLAND_PARK			33
#define MAP_AREA_HALLS_OF_THE_DRAGON_KING		34
#define MAP_AREA_FOREST_OF_THE_SINO_CLAN		35
#define MAP_AREA_VILLAGE_OF_THE_PYGMIES			36
#define MAP_AREA_PLAINS_OF_LANDOVER			37
#define MAP_AREA_FOREST_OF_THE_ELVEN_KING		38
#define MAP_AREA_FOREST_OF_THE_SMURFS			39
#define MAP_AREA_CASTLE_OF_THE_SMURFS			40
#define MAP_AREA_SWAMP_OF_THE_ZOMBIES			41
#define MAP_AREA_VILLAGE_OF_THE_CENTAUR_CLAN		42
#define MAP_AREA_VILLAGE_OF_THE_CAG_TROLLS		43
#define MAP_AREA_VOLCANO_COLLEGE_OF_FLAME		44
#define MAP_AREA_VILLAGE_OF_THE_HOBBITS			45
#define MAP_AREA_CAVERNS_OF_THE_DWARVES			46

#endif /* MAP_AREA_DEFS_H */
